// <auto-generated />
namespace book_store_for_developers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addField));
        
        string IMigrationMetadata.Id
        {
            get { return "202108211800273_addField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
